name: 'Trigger CloudBees Workflow'
description: 'Trigger CloudBees workflow from GitHub Actions workflow'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: true
  cloudbees-pat:
    description: 'The CloudBees platform personal access token.'
    required: true
  component-id:
    description: 'The Component-id of the CloudBees workflow to be triggered. '
    required: false
  branch-name:
    description: 'The branch of the CloudBees workflow to be triggered.'
    required: false
  workflow-file-name:
    description: 'The name of the CloudBees workflow to be triggered.'
    required: true
  workflow-inputs:
    description: 'Input parameters to be passed to trigger the workflow. Represented as key-value pairs, where keys and values are both strings.'
    required: false

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "docker"
  steps:
    - name: Set Greeting
      uses: "docker://ghcr.io/karthiknaveene/gha-action/my-app:latest"  # @TODO: Add the image
      env:
        CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
        CLOUDBEES_API_TOKEN: ${{ inputs.cloudbees-pat }}
        COMPONENT_ID: ${{ inputs.component-id }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        WORKFLOW_FILE_NAME: ${{ inputs.workflow-file-name }}
        WORKFLOW_INPUTS: ${{ inputs.workflow-inputs }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

  

