apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      image-name:
        type: string
        required: true
      image-version:
        type: string
        required: true
      url:
          type: string
          required: true
      digest:
          type: string
          required: true
jobs:
  deploy:
    steps:
      - name: Say hello
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ inputs.image-version }}
          url:  ${{ inputs.url }}
          digest:  ${{ inputs.digest }}
          target-environment: PREPROD
          name:  ${{ inputs.image-name }}