name: Test My Go Action

on:
   push:
    branches:
      - test-branchq
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: cloudbees-gha-cbp/run-cloudbees-workflow@main
        id: go-action
        with :
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          workflow-file-name: "workflow6.yaml"
      

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
      
        
      
    
