name: Test My Go Action

on:
   push:
    branches:
      - run-cloudbees-workflow
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: cloudbees-gha-cbp/run-cloudbees-workflow@main
        id: go-action
        with :
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          component-id: "20360000-ce0e-4c39-ace8-65a6f0803bee"
          branch-name: "test"
          workflow-file-name: "cb-workflow.yaml"

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
      
        
      
    
