name: Test My Go Action

on:
   push:
    branches:
      - test-branch
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: cloudbees-gha-cbp/run-cloudbees-workflow@CBP-10930-v1
        id: go-action
        with :
          #cloudbees-url:  "https://api.cloudbees.io/a"
          #cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          #cloudbees-pat: "invalid"
          #component-id: "395bb7a1-0380-429a-9638-3b33a5e6d026"
          #component-id: "invalid"
          #component-id: "f3e68eeb-fb25-40b0-86b1-66e504a1ba75"
          #workflow-inputs: '{"workflowinput1": "test1"}'
          cloudbees-pat: ${{ secrets.QA_PAT }}
          #component-id: "e46d6663-5516-4aaa-b0ab-60b0d8ebccea"
          #branch-name: "test"
          workflow-file-name: "workflow6.yaml"

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
      
        
      
    
