name: Test My Go Action

on:
   push:
    branches:
      - run-cloudbees-workflow
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run My Custom Go Action
        uses: cloudbees-io-gha/run-cloudbees-workflow@v1
        id: go-action
        with :
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          branch-name: "test-branch"
          workflow-file-name: "workflow6.yaml"

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"

      - name: Publish evidence to Platform
        uses: cloudbees-io-gha/publish-evidence-item@v1
        with:
          cloudbees-pat:  ${{ secrets.PROD_PAT }}
          content: "test publish evidence"

      - name: Publish test results to Platform
        uses: cloudbees-io-gha/publish-test-results@v1
        with:
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          test-type: go
          results-path: ${{ cloudbees.workspace }}/test_reports

      - name: Register build artifacts in Platform
        uses: cloudbees-io-gha/register-build-artifact@v1
        with:
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          component-id: "1c0f4482-bd89-4489-8c86-313128f2f44a"
          name: "test-1"
          version: "v1.0.3"
          url: "test-1:1.0.3"
          digest: "test-digest"
          

          
        
   
        
      
    
