name: Test My Go Action

on:
   push:
    branches:
      - test-branch
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: cloudbees-gha-cbp/run-cloudbees-workflow@test
        id: go-action
        with :
          #cloudbees-url:  "https://api.cloudbees.io/a"
          #cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          #cloudbees-pat: "invalid"
          #component-id: "395bb7a1-0380-429a-9638-3b33a5e6d026"
          #component-id: "invalid"
          #component-id: "f3e68eeb-fb25-40b0-86b1-66e504a1ba75"
          #workflow-inputs: '{"workflowinput1qa": "test1"}'
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          #component-id: "20360000-ce0e-4c39-ace8-65a6f0803bee"
          #branch-name: "main"
          workflow-file-name: "workflow6.yaml"
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
      
        
      
    
