name: TEST
on:
  schedule:
     - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world!"
