name: Test My Go Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: karthiknaveene/gha-action@main
        id: go-action
        with :
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          cloudbees-pat: ${{ secrets.MY_PAT }}
          component_id: "395bb7a1-0380-429a-9638-3b33a5e6d026"
          branch_name: "workflowTest1"
          workflow_file_name: "workflow-test-1.yaml"

