name: Testresults

on:
   push:
    branches:
      - gha
   workflow_dispatch:
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: apache/commons-lang
          
      - name: Run Tests with Maven
        run: |
          mvn test -Dtest=StringUtilsTest
          ls -lrt
          
      - name: Upload Test Results to GitHub Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-results
          path: target/surefire-reports/*

          


          

          
        
   
        
      
    
