name: Test My Go Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up environment variable for PAT
        run: echo "MY_PAT=${{ secrets.MY_PAT }}"

      # - name: Log in to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_PAT }}

      # - name: Pull Docker image
      #   run: |
      #     docker pull ghcr.io/karthiknaveene/gha-action/gha-run-cbp-workflow:latest\

      - name: Run My Custom Go Action
        uses: cloudbees-gha-cbp/run-cloudbees-workflow@CBP-12046
        id: go-action
        with :
          cloudbees-url: "https://api.saas-qa.beescloud.com/"
          cloudbees-pat: ${{ secrets.QA_PAT }}
          #cloudbees-pat: "invalid"
          #component-id: "395bb7a1-0380-429a-9638-3b33a5e6d026"
          component-id: "f3e68eeb-fb25-40b0-86b1-66e504a1ba75"
          branch-name: "test-branch"
          workflow-file-name: "my-workflow.yaml"
          #workflow-inputs: '{"workflowinput1": "test1"}'
          

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
        
