name: Test My Go Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up environment variable for PAT
        run: echo "MY_PAT=${{ secrets.MY_PAT }}"

      - name: Run My Custom Go Action
        uses: karthiknaveene/gha-action@main
        id: go-action
        with :
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          cloudbees-pat: ${{ secrets.MY_PAT }}
          #cloudbees-pat: ${{ secrets.MY_PAT }}
          #component-id: "0a93f2dc-ae5c-4246-ab82-3db8c8328284"
          component-id: "395bb7a1-0380-429a-9638-3b33a5e6d026"
          branch-name: "workflowTest1"
          #branch-name: "main"
          workflow-file-name: "workflow-test-1.yaml"
          #workflow-file-name: "go-publish-results-using-json"
          workflow-inputs: '{"workflowinput1": "test1"}'

      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
        
