name: Testresults

on:
   push:
    branches:
      - gha
   workflow_dispatch:
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: apache/commons-lang
          
      - name: Run Tests with Maven
        run: |
          mvn test -Dtest=StringUtilsTest
          ls -lrt
          
      - name: Run My Custom Go Action for GO
        uses: cloudbees-io-gha/publish-test-results@v2
        with:
          test-type: JUNIT
          results-path: target/surefire-reports/*

          


          

          
        
   
        
      
    
