name: Test My Go Action

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run CloudBees platform workflow
        uses: cloudbees-io-gha/run-cloudbees-workflow@v1
        id: go-action
        with:
          cloudbees-url:  "https://api.saas-qa.beescloud.com/"
          workflow-file-name: "workflow.yaml"
          workflow-inputs: '{"workflowinput1": "test1"}'

      # - name: Checkout Repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: apache/commons-lang
      # - name: Run Tests with Maven
      #   run: |
      #     mvn test -Dtest=StringUtilsTest
      #     ls -lrt
      # - name: Run My Custom Go Action for GO - OIDC
      #   uses: cloudbees-io-gha/publish-test-results@v2
      #   with:
      #     test-type: JUNIT
      #     results-path: target/surefire-reports/*

      - name: Checkout Repository - v1
        uses: actions/checkout@v3
        with:
          repository: apache/commons-lang
      - name: Run Tests with Maven - v1
        run: |
          mvn test -Dtest=StringUtilsTest
          ls -lrt
          
      - name: Run My Custom Go Action for GO - V1 
        uses: cloudbees-io-gha/publish-test-results@v2
        with:
          test-type: JUNIT
          results-path: target/surefire-reports/*
          cloudbees-url:  "https://api.saas-qa.beescloud.com/"
      
      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"

        
