name: Test My Go Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Run CloudBees platform workflow
        uses: karthiknaveene/gha-action@main
        #uses: cloudbees-io-gha/run-cloudbees-workflow@v1
        id: go-action
        with:
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          cloudbees-pat:  ${{ secrets.PREPROD_PAT }}
          workflow-file-name: "workflow.yaml"
          workflow-inputs: '{"workflowinput1": "test1"}'

      - name: Append Docker output to $GITHUB_OUTPUT
        run: |
          cat /app/output/custom_output >> $GITHUB_OUTPUT
          
      
      - name: Use runUrl output
        run: echo "The CloudBees run URL is ${{ steps.go-action.outputs.cbp_run_url}}"
        
  
