name: Test My Go Action

on:
  workflow_dispatch:

jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: karthiknaveene/gha-action@main
        id: go-action
        with :
          cloudbees-url: "agvs"
          cloudbees-pat: "hjavbsx"
          component-id : "jhabsx"
          branch-name : "hjsxbv"
          workflow-file-name: "jzhbx"