name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, this workflow was manually triggered!"
